---
title: ""
---
<br>
  
**Articles in refereed journals**   

Ariel, B. & Partridge, H. (2016) [Predictable Policing: Measuring the Crime Control Benefits of Hotspots Policing at Bus Stops](http://link.springer.com/article/10.1007/s10940-016-9312-y). Journal of Quantitative Criminology.DOI: 10.1007/s10940-016-9312-y

Newton, A., Partridge, H. & Gill, A. (2014) [In and around: Identifying predictors of theft within and near to major mass underground transit systems.](http://www.palgrave-journals.com/sj/journal/v27/n2/abs/sj20142a.html) Security Journal, 27, 132–146.

Newton, A., Partridge, H. & Gill, A. (2014) [Above and below: measuring crime risk in and around underground mass transit systems.](http://link.springer.com/article/10.1186/2193-7680-3-1) Crime Science, 3:1.

Gill, A., Partridge, H., &  Newton, A. (2014) [Interstitial Crime Analysis.](http://www.ucl.ac.uk/jdibrief/analysis/interstitial-crime-analysis) JDiBrief Series. London: UCL Jill Dando Institute of Security and Crime Science. ISSN 2050-4853

Partridge, H. (2013) [Hot Routes.](http://www.ucl.ac.uk/jdibrief/analysis/hot-routes) JDiBrief Series. London: UCL Jill Dando Institute of Security and Crime Science. ISSN 2050-4853

Partridge, H. (2012) [The determinants of and barriers to critical consumption: a study of Addiopizzo.](http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=10048803&fulltextType=RA&fileId=S1353294400000570) Modern Italy 17 (3): 343-363.

Tompson, L., Partridge, H. & Shepherd, N. (2009) [Hot Routes: Developing a New Technique for the Spatial Analysis of Crime.](http://discovery.ucl.ac.uk/20057/) Crime Mapping: A Journal of Research and Practice 1 (1): 77-96.

**Book chapters**   

Newton, A., Partridge, H. and Gill, A. (2015) [In and Around. Identifying In and around: Identifying predictors of theft within and near to major mass underground transit systems.](http://www.palgrave.com/us/book/9781137457646) In: Safety and Security in Transit Environments: An Interdisciplinary Approach. London, UK: Palgrave Macmillan. pp. 76-98. ISBN 9781137457646

**Selected presentations**   

[Advancing crime analysis with R and Shiny.](https://speakerdeck.com/pracademic/advancing-crime-analysis-with-r-and-shiny) International Crime and Intelligence Analysis Conference, 25-26 February 2016, Manchester.

[Using Shiny to Visualise Crime and Collision Data.](https://speakerdeck.com/pracademic/using-shiny-to-visualise-crime-and-collision-data) Data Visualisation Summit, London, 11 November 2015.

[The London “Hot Buses” Patrol Experiment.](https://speakerdeck.com/pracademic/the-london-hot-buses-patrol-experiment) Institute of Criminology, Cambridge University, 16 December 2014.

[Does bus-related crime ‘float in space’?](https://speakerdeck.com/pracademic/does-bus-related-crime-float-in-space) Streets, Transport and Crime seminar, UCL Transport Institute, Westminster, 26 February 2014.

[Reducing cycle theft - Le azioni di contrasto a Londra.](https://speakerdeck.com/pracademic/reducing-cycle-theft-le-azioni-di-contrasto-a-londra) Federazione Italiana Amici della Bicicletta conference, Milan,  21 November 2013.

[Hot Routes - developing a technique for the spatial analysis of bus crime in London.]() Presented with Naomi Shepherd. National Crime Mapping Conference, Manchester, 29 July 2008.
